"""Single registry of CSV fields for export, import-create and import-update.

Every exporter, the importer's header map and the update path read from this
list. A field that must survive export -> import is marked ``round_trip``; the
generated round-trip test covers each of them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass(frozen=True)
class CsvField:
    target: str | None
    header: str
    aliases: tuple[str, ...] = field(default=())
    export: bool = True
    create: bool = True
    update: bool = False
    round_trip: bool = False
    frontend_key: str | None = None


def normalise_header(raw: str) -> str:
    """Normalize a CSV header to the importer's matching form."""
    s = raw.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


FIELDS: tuple[CsvField, ...] = (
    CsvField("license_ref", "license_ref", aliases=("lt_ref",), frontend_key="licenseRef"),
    CsvField(
        "external_ref",
        "external_ref",
        update=True,
        round_trip=True,
        frontend_key="externalRef",
    ),
    CsvField(
        "publisher_name",
        "publisher_name",
        aliases=("publisher",),
        update=True,
        round_trip=True,
        frontend_key="publisher",
    ),
    CsvField(
        "software_description",
        "software_description",
        aliases=("description",),
        update=True,
        round_trip=True,
        frontend_key="description",
    ),
    CsvField(
        "contract_number",
        "contract_number",
        aliases=("contract", "contract_no"),
        update=True,
        round_trip=True,
        frontend_key="contractNumber",
    ),
    CsvField(
        "po_number",
        "po_number",
        aliases=("po", "purchase_order_no"),
        update=True,
        round_trip=True,
        frontend_key="poNumber",
    ),
    # Generated by LicenseTrack. New records keep the file's number when it is
    # free; updates ignore it (see import_workflow.prepare_import_rows).
    # "Item" is the PO line in purchasing exports (Flexera among them); the
    # product text there is "Description".
    CsvField(
        "po_line_number",
        "po_line",
        aliases=("po_line_number", "po_line_item", "po_line_no", "item"),
        update=False,
        round_trip=True,
        frontend_key="poLineNumber",
    ),
    CsvField(
        "procurement_reference",
        "procurement_reference",
        aliases=("procurement_ref",),
        update=True,
        round_trip=True,
        frontend_key="procurementReference",
    ),
    CsvField(
        "invoice_number",
        "invoice_number",
        aliases=("invoice",),
        update=True,
        round_trip=True,
        frontend_key="invoiceNumber",
    ),
    CsvField(
        "contact_email",
        "contact_email",
        aliases=("publisher_contact", "supplier_contact"),
        update=True,
        round_trip=True,
        frontend_key="contactEmail",
    ),
    CsvField(
        "supplier",
        "supplier",
        aliases=("vendor",),
        update=True,
        round_trip=True,
        frontend_key="supplier",
    ),
    CsvField(
        "cost_centre",
        "cost_centre",
        aliases=("cost_center", "department"),
        update=True,
        round_trip=True,
        frontend_key="costCentre",
    ),
    CsvField(
        "budget_owner_email",
        "budget_owner_email",
        aliases=("budget_owner",),
        update=True,
        round_trip=True,
        frontend_key="budgetOwnerEmail",
    ),
    CsvField(
        "secondary_contacts",
        "secondary_contacts",
        aliases=(
            "secondary_contact",
            "secondary_contact_email",
            "application_owner",
            "application_owner_email",
            "app_owner",
            "app_owner_email",
            "technical_owner",
            "technical_owner_email",
            "application_owner_email_address",
        ),
        update=True,
        round_trip=True,
        frontend_key="secondaryContacts",
    ),
    CsvField(
        "license_type",
        "license_type",
        aliases=("type", "purchase_type"),
        round_trip=True,
        frontend_key="licenseType",
    ),
    CsvField(
        "type_description",
        "type_description",
        update=True,
        round_trip=True,
        frontend_key="typeDescription",
    ),
    CsvField(
        "is_renewable",
        "is_renewable",
        aliases=("renewable",),
        update=True,
        round_trip=True,
        frontend_key="isRenewable",
    ),
    CsvField(
        "license_metric",
        "license_metric",
        aliases=("metric",),
        update=True,
        round_trip=True,
        frontend_key="licenseMetric",
    ),
    CsvField(
        "quantity",
        "quantity",
        aliases=("qty", "purchase_quantity"),
        update=True,
        round_trip=True,
        frontend_key="quantity",
    ),
    CsvField("effective_quantity", "effective_quantity", frontend_key="effectiveQuantity"),
    CsvField(
        "quantity_per_unit",
        "quantity_per_unit",
        aliases=("qty_per_unit",),
        update=True,
        round_trip=True,
        frontend_key="quantityPerUnit",
    ),
    CsvField(
        "sku_code",
        "sku_code",
        aliases=("sku", "part_no_sku"),
        update=True,
        round_trip=True,
        frontend_key="skuCode",
    ),
    CsvField(
        "unit_price",
        "unit_price",
        aliases=("unit_price_eur",),
        update=True,
        round_trip=True,
        frontend_key="unitPrice",
    ),
    # Line Total is always quantity x unit price. An imported line total only
    # fills a missing unit price or is checked; it is never stored.
    CsvField(
        "line_total",
        "line_total",
        aliases=("line_total_eur", "total_price_eur"),
        frontend_key="calcTotal",
    ),
    # Pre-1.2.0 per-line "Total PO Price" (often a whole-PO value): recognized
    # so the importer can warn, never imported.
    CsvField("legacy_po_price", "total_po_price", export=False),
    CsvField(
        "po_total_override",
        "po_total_manual",
        aliases=("manual_po_total", "po_total_override"),
        round_trip=True,
        frontend_key="poTotalOverride",
    ),
    CsvField("currency", "currency", update=True, round_trip=True, frontend_key="currency"),
    CsvField(
        "start_date",
        "start_date",
        aliases=("effective_date",),
        update=True,
        round_trip=True,
        frontend_key="startDate",
    ),
    CsvField(
        "end_date",
        "end_date",
        aliases=("expiry_date", "contractenddate"),
        update=True,
        round_trip=True,
        frontend_key="endDate",
    ),
    CsvField(
        "notice_date",
        "notice_date",
        aliases=("notice_deadline",),
        update=True,
        round_trip=True,
        frontend_key="noticeDate",
    ),
    CsvField(
        "request_date",
        "request_date",
        update=True,
        round_trip=True,
        frontend_key="requestDate",
    ),
    # Purchase Date is a procurement milestone, not a Flexera start-date fallback.
    CsvField(
        "purchase_date",
        "purchase_date",
        update=True,
        round_trip=True,
        frontend_key="purchaseDate",
    ),
    CsvField("portal_url", "portal_url", update=True, round_trip=True, frontend_key="portalUrl"),
    CsvField("notes", "notes", update=True, round_trip=True, frontend_key="notes"),
    CsvField(
        "parent_license_refs",
        "parent_license_refs",
        aliases=("parent_license_ref", "parent_ref", "parent"),
        round_trip=True,
        frontend_key="parentLicenseRefs",
    ),
    CsvField(
        "maintenance_coverage",
        "maintenance_coverage",
        aliases=(
            "maintenance_support_coverage",
            "includes_maintenance",
            "include_maintenance",
            "maintenance_included",
            "purchase_includes_maintenance",
            "purchase_includes_support",
            "includes_support",
        ),
        update=True,
        round_trip=True,
        frontend_key="maintenanceCoverage",
    ),
    CsvField(
        "maintenance_start_date",
        "maintenance_start_date",
        aliases=(
            "maintenance_start",
            "support_start",
            "support_start_date",
            "coverage_start",
            "coverage_start_date",
        ),
        update=True,
        round_trip=True,
        frontend_key="maintenanceStartDate",
    ),
    CsvField(
        "maintenance_end_date",
        "maintenance_end_date",
        aliases=(
            "maintenance_end",
            "support_end",
            "support_end_date",
            "coverage_end",
            "coverage_end_date",
        ),
        update=True,
        round_trip=True,
        frontend_key="maintenanceEndDate",
    ),
    CsvField(
        "maintenance_cost",
        "maintenance_cost",
        aliases=(
            "support_cost",
            "total_support_cost",
            "total_support_cost_eur",
            "coverage_cost",
        ),
        update=True,
        round_trip=True,
        frontend_key="maintenanceCost",
    ),
    CsvField(
        "maintenance_pricing_basis",
        "maintenance_pricing_basis",
        aliases=("support_pricing_basis",),
        update=True,
        round_trip=True,
        frontend_key="maintenancePricingBasis",
    ),
    CsvField(
        "maintenance_quantity",
        "maintenance_quantity",
        update=True,
        round_trip=True,
        frontend_key="maintenanceQuantity",
    ),
    CsvField(
        "maintenance_unit_price",
        "maintenance_unit_price",
        update=True,
        round_trip=True,
        frontend_key="maintenanceUnitPrice",
    ),
    # Export-only / computed fields recognized but intentionally ignored on import.
    CsvField(
        None,
        "license_record_id",
        aliases=("id",),
        create=False,
        frontend_key="recordId",
    ),
    CsvField(None, "docs", create=False),
    CsvField(None, "calc_total", create=False, export=False),
    CsvField(None, "expiration", create=False),
    CsvField(None, "complete", create=False),
    # Total PO Value is a derived whole-PO aggregate, not a per-license line total.
    CsvField(None, "total_po_value", create=False, frontend_key="totalPoPrice"),
    CsvField(None, "created_at", aliases=("created",), create=False),
    CsvField(None, "created_by", create=False),
    CsvField(None, "updated_at", aliases=("last_updated",), create=False),
    CsvField(None, "last_synced_at", aliases=("last_synced",), create=False),
    CsvField(
        "lifecycle_status",
        "lifecycle_status",
        round_trip=True,
        frontend_key="lifecycleStatus",
    ),
    CsvField(None, "sync_status", create=False),
)


def header_map() -> dict[str, str]:
    mapping: dict[str, str] = {}
    for csv_field in FIELDS:
        if csv_field.target is None:
            continue
        for name in (csv_field.header, *csv_field.aliases):
            mapping[normalise_header(name)] = csv_field.target
    return mapping


def ignored_headers() -> frozenset[str]:
    names: set[str] = set()
    for csv_field in FIELDS:
        if csv_field.target is None:
            names.update(normalise_header(name) for name in (csv_field.header, *csv_field.aliases))
    return frozenset(names)


def frontend_export_headers() -> dict[str, str]:
    return {
        csv_field.frontend_key: csv_field.header
        for csv_field in FIELDS
        if csv_field.frontend_key and csv_field.export
    }


if __name__ == "__main__":
    import json
    import sys
    from pathlib import Path

    output = Path(sys.argv[1])
    output.write_text(
        json.dumps({"exportHeaders": frontend_export_headers()}, indent=2, sort_keys=True) + "\n"
    )
