"""remove_show_contracts_from_user_settings

Revision ID: 230f1ca1fe2c
Revises: 8a0c5a6f4048
Create Date: 2026-03-22 15:56:03.371008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230f1ca1fe2c'
down_revision: Union[str, None] = '8a0c5a6f4048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('show_contracts')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_contracts', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
