"""add_notification_send_hour

Revision ID: 2bba66c9c984
Revises: d401555ca039
Create Date: 2026-03-07 09:38:52.223594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bba66c9c984'
down_revision: Union[str, None] = 'd401555ca039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_send_hour', sa.Integer(), nullable=False, server_default='7'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('notification_send_hour')

    # ### end Alembic commands ###
