"""add number_format_locale to user_settings

Revision ID: 4172153725b2
Revises: b8e3f9a2c1d5
Create Date: 2026-03-13 18:15:46.608334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4172153725b2'
down_revision: Union[str, None] = 'b8e3f9a2c1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_format_locale', sa.String(length=10), nullable=False, server_default='en-US'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('number_format_locale')

    # ### end Alembic commands ###
