"""add portal_url to licenses

Revision ID: 4df00001d9a2
Revises: 230f1ca1fe2c
Create Date: 2026-03-28 01:31:48.646603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df00001d9a2'
down_revision: Union[str, None] = '230f1ca1fe2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_column('portal_url')

    # ### end Alembic commands ###
