"""add custom field definitions and values

Revision ID: 5379967bd20c
Revises: 4df00001d9a2
Create Date: 2026-03-28 16:58:40.480339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5379967bd20c'
down_revision: Union[str, None] = '4df00001d9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('license_custom_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('custom_field_def_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_currency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['custom_field_def_id'], ['custom_field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'custom_field_def_id', name='uq_license_custom_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_custom_values')
    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
