"""add_storage_path_to_global_settings

Revision ID: 5a8e1b80b461
Revises: a3c9f2e1b4d7
Create Date: 2026-03-06 18:11:21.490076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8e1b80b461'
down_revision: Union[str, None] = 'a3c9f2e1b4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
