"""add sidebar_collapsed to user_settings

Revision ID: 5d55a89d61f0
Revises: c177cee4b099
Create Date: 2026-03-08 00:08:29.270638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d55a89d61f0'
down_revision: Union[str, None] = 'c177cee4b099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sidebar_collapsed', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('sidebar_collapsed')

    # ### end Alembic commands ###
