"""add_notification_fields_to_global_settings

Revision ID: 6960a7316d7d
Revises: 5a8e1b80b461
Create Date: 2026-03-07 00:04:41.020498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6960a7316d7d'
down_revision: Union[str, None] = '5a8e1b80b461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_days', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('manager_email', sa.String(length=255), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('manager_email')
        batch_op.drop_column('notification_days')

    # ### end Alembic commands ###
