"""add_section_to_custom_field_definitions

Revision ID: 757485dbe08a
Revises: f376339d6e7c
Create Date: 2026-04-12 21:29:23.193218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757485dbe08a'
down_revision: Union[str, None] = 'f376339d6e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
