"""add_license_ref_and_external_fields

Revision ID: 82f2821071cd
Revises: f09479cea41f
Create Date: 2026-04-11 11:32:10.879497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f2821071cd'
down_revision: Union[str, None] = 'f09479cea41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_ref_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_ref', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_licenses_license_ref'), ['license_ref'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_license_ref'))
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('external_ref')
        batch_op.drop_column('license_ref')

    op.drop_table('license_ref_sequence')
    # ### end Alembic commands ###
