"""add_contracts_enabled_to_global_settings

Revision ID: 8a0c5a6f4048
Revises: 94cf8ee55799
Create Date: 2026-03-22 15:55:41.645981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0c5a6f4048'
down_revision: Union[str, None] = '94cf8ee55799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contracts_enabled', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('contracts_enabled')

    # ### end Alembic commands ###
