"""add_email_enabled_to_global_settings

Revision ID: 94cf8ee55799
Revises: 8dc152c9a886
Create Date: 2026-03-21 21:41:06.219941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cf8ee55799'
down_revision: Union[str, None] = '8dc152c9a886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_enabled', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('sourcing_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sourcing_items_renewal_for_license_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcing_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sourcing_items_renewal_for_license_id'), ['renewal_for_license_id'], unique=False)

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('email_enabled')

    # ### end Alembic commands ###
