"""add_display_currency_column_order_saved_views

Revision ID: c177cee4b099
Revises: 2bba66c9c984
Create Date: 2026-03-07 11:12:27.449068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c177cee4b099'
down_revision: Union[str, None] = '2bba66c9c984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency', sa.String(length=10), nullable=False, server_default='EUR'))
        batch_op.add_column(sa.Column('column_order', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('saved_views', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('saved_views')
        batch_op.drop_column('column_order')
        batch_op.drop_column('display_currency')

    # ### end Alembic commands ###
