"""license_ref_drop_unique_constraint

Revision ID: cc0ded1214ae
Revises: 82f2821071cd
Create Date: 2026-04-11 11:58:36.497232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0ded1214ae'
down_revision: Union[str, None] = '82f2821071cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_license_ref'))
        batch_op.create_index(batch_op.f('ix_licenses_license_ref'), ['license_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_license_ref'))
        batch_op.create_index(batch_op.f('ix_licenses_license_ref'), ['license_ref'], unique=1)

    # ### end Alembic commands ###
