"""add_smtp_fields_to_global_settings

Revision ID: d401555ca039
Revises: 6960a7316d7d
Create Date: 2026-03-07 00:05:30.885116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd401555ca039'
down_revision: Union[str, None] = '6960a7316d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_host', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=False, server_default='587'))
        batch_op.add_column(sa.Column('smtp_username', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('smtp_sender', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('smtp_use_tls', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('smtp_use_tls')
        batch_op.drop_column('smtp_sender')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_username')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_host')

    # ### end Alembic commands ###
