"""initial_schema

Revision ID: df9b4eee3740
Revises: 
Create Date: 2026-02-28 00:11:18.433344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9b4eee3740'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandatory_fields', sa.JSON(), nullable=False),
    sa.Column('auth_method', sa.String(length=20), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('licenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publisher_name', sa.String(length=255), nullable=False),
    sa.Column('software_description', sa.String(length=500), nullable=False),
    sa.Column('license_type', sa.Enum('subscription', 'perpetual', 'maintenance', 'saas', 'oem', 'freeware', name='licensetype'), nullable=False),
    sa.Column('license_metric', sa.Enum('per_user', 'per_device', 'per_cpu', 'per_core', 'site', 'concurrent', 'enterprise', name='licensemetric'), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.String(length=50), nullable=False),
    sa.Column('total_po_price', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_number', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=200), nullable=False),
    sa.Column('invoice_number', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('cost_centre', sa.String(length=255), nullable=False),
    sa.Column('budget_owner_email', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('renewed_from_id', sa.Integer(), nullable=True),
    sa.Column('renewed_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['renewed_from_id'], ['licenses.id'], name='fk_license_renewed_from', use_alter=True),
    sa.ForeignKeyConstraint(['renewed_to_id'], ['licenses.id'], name='fk_license_renewed_to', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visible_in_list', sa.JSON(), nullable=False),
    sa.Column('visible_in_detail', sa.JSON(), nullable=False),
    sa.Column('notification_days', sa.Integer(), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('invoice', 'eula', 'entitlement', name='documentcategory'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_license_id'), ['license_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_license_id'))

    op.drop_table('documents')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    op.drop_table('licenses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
