"""add_allowed_email_domains_to_global_settings

Revision ID: f1e2994e3093
Revises: 5d55a89d61f0
Create Date: 2026-03-08 21:09:52.274622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e2994e3093'
down_revision: Union[str, None] = '5d55a89d61f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_email_domains', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('allowed_email_domains')

    # ### end Alembic commands ###
