"""add_pending_orders

Revision ID: f526effc8ebf
Revises: ff42c1be0633
Create Date: 2026-03-01 18:22:26.941473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f526effc8ebf'
down_revision: Union[str, None] = 'ff42c1be0633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=255), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'invoice_received', 'converted', name='pendingorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sourcing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sourcing_items_pending_order_id', 'pending_orders', ['pending_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcing_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sourcing_items_pending_order_id', type_='foreignkey')
        batch_op.drop_column('pending_order_id')

    op.drop_table('pending_orders')
    # ### end Alembic commands ###
