"""add backup settings to global_settings

Revision ID: f63942c11a59
Revises: 4172153725b2
Create Date: 2026-03-13 20:12:05.084157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63942c11a59'
down_revision: Union[str, None] = '4172153725b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_location', sa.String(length=500), nullable=False, server_default='./backups'))
        batch_op.add_column(sa.Column('backup_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('backup_hour', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('backup_keep', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('backup_keep')
        batch_op.drop_column('backup_hour')
        batch_op.drop_column('backup_enabled')
        batch_op.drop_column('backup_location')

    # ### end Alembic commands ###
