export const queryKeys = {
  licenses: ["licenses"],
  renewals: ["renewals"],
  sourcing: ["sourcing"],
  sourcingHistory: ["sourcing-history"],
  sourcingItems: ["sourcing-items"],
  pendingOrders: ["pending-orders"],
  pendingOrderHistory: ["pending-order-history"],
  contracts: ["contracts"],
  notifications: ["notifications"],
  portfolioStats: ["portfolio-stats"],
  reportsPortfolioStats: ["reports-portfolio-stats"],
  licenseStats: ["license-stats"],
  licenseProcurementTrail: (licenseId) => ["license-procurement-trail", licenseId],
  customFieldDefs: ["custom-field-defs"],
  referenceData: ["reference-data"],
  referenceDataSearch: (kind, search = "") => ["reference-data", kind, search],
};
